@url = http://localhost:{{$dotenv VITE_PORT}}
@token = {{$dotenv VITE_TOKEN}}

### GET VERSION INFO
GET {{url}}/
Authorization: Bearer {{token}}

### GET USER INFO
GET {{url}}/users
Authorization: Bearer {{token}}

### GET SHIFT INFO
GET {{url}}/shifts
Authorization: Bearer {{token}}

### === CRUD =======================

### GET EMPLOYEES
GET {{url}}/employees
Authorization: Bearer {{token}}

### GET EMPLOYEE
GET {{url}}/employees/1
Authorization: Bearer {{token}}

### CREATE EMPLOYEE
POST {{url}}/employees
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"firstName": "Ralf2",
	"lastName": "Zenter",
	"age": 30
}

### DELETE EMPLOYEE
DELETE {{url}}/employees/6
Authorization: Bearer {{token}}

### REPLACE EMPLOYEE
PUT {{url}}/employees/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"firstName": "Ralf",
	"lastName": "Indexer",
	"age": 34
}


### === NORTHWIND ====================

### NORTHWIND CATEGORIES
GET {{url}}/northwind/categories
Authorization: Bearer {{token}}

### NORTHWIND CUSTOMERS
GET {{url}}/northwind/customers
Authorization: Bearer {{token}}

### NORTHWIND EMPLOYEES
GET {{url}}/northwind/employees
Authorization: Bearer {{token}}

### NORTHWIND ORDERS
GET {{url}}/northwind/orders
Authorization: Bearer {{token}}

### NORTHWIND PRODUCTS
GET {{url}}/northwind/products
Authorization: Bearer {{token}}

### NORTHWIND REGIONS
GET {{url}}/northwind/regions
Authorization: Bearer {{token}}

### NORTHWIND SHIPPERS
GET {{url}}/northwind/shippers
Authorization: Bearer {{token}}

### NORTHWIND SUPPLIERS
GET {{url}}/northwind/suppliers
Authorization: Bearer {{token}}
