@url = {{$dotenv API_URL}}
@token = {{$dotenv TOKEN}}

### GET VERSION INFO
GET {{url}}/
Authorization: Bearer {{token}}

### GET EMPLOYEE INFO
GET {{url}}/employees
Authorization: Bearer {{token}}

### GET USER INFO
GET {{url}}/users
Authorization: Bearer {{token}}

### GET SHIFT INFO
GET {{url}}/shifts
Authorization: Bearer {{token}}